# Generated by Django 4.0.4 on 2022-09-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmd1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
